name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Build
      run: go build -v ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ISHC
        path: |
          ./myproject # replace with your actual build output path
          !**/tests/**
